// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto_financeiro_mvc.Data;

#nullable disable

namespace projeto_financeiro_mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250909234302_relacionamentoUsuario_grupofamiliar")]
    partial class relacionamentoUsuario_grupofamiliar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projeto_financeiro_mvc.Models.ContaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupoFamiliarId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Saldo")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFamiliarId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.GrupoFamiliarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GrupoFamiliar");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.LancamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupoFamiliarId")
                        .HasColumnType("int");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<int>("Parcelas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Previsao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("GrupoFamiliarId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.RecorrenteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupoFamiliarId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRecorrente")
                        .HasColumnType("bit");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<int>("Parcelas")
                        .HasColumnType("int");

                    b.Property<DateTime>("Previsao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("GrupoFamiliarId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recorrentes");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.TransferenciaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContaDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("ContaOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCompensacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataTransferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupoFamiliarId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId");

                    b.HasIndex("ContaOrigemId");

                    b.HasIndex("GrupoFamiliarId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupoFamiliarId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoFamiliarId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.ContaModel", b =>
                {
                    b.HasOne("projeto_financeiro_mvc.Models.GrupoFamiliarModel", "GrupoFamiliar")
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId");

                    b.HasOne("projeto_financeiro_mvc.Models.UsuarioModel", "Usuario")
                        .WithMany("Contas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoFamiliar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.LancamentoModel", b =>
                {
                    b.HasOne("projeto_financeiro_mvc.Models.ContaModel", "Conta")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaId");

                    b.HasOne("projeto_financeiro_mvc.Models.GrupoFamiliarModel", "GrupoFamiliar")
                        .WithMany("Lancamentos")
                        .HasForeignKey("GrupoFamiliarId");

                    b.HasOne("projeto_financeiro_mvc.Models.UsuarioModel", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("GrupoFamiliar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.RecorrenteModel", b =>
                {
                    b.HasOne("projeto_financeiro_mvc.Models.ContaModel", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId");

                    b.HasOne("projeto_financeiro_mvc.Models.GrupoFamiliarModel", "GrupoFamiliar")
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId");

                    b.HasOne("projeto_financeiro_mvc.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("GrupoFamiliar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.TransferenciaModel", b =>
                {
                    b.HasOne("projeto_financeiro_mvc.Models.ContaModel", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("projeto_financeiro_mvc.Models.ContaModel", "ContaOrigem")
                        .WithMany()
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("projeto_financeiro_mvc.Models.GrupoFamiliarModel", "GrupoFamiliar")
                        .WithMany()
                        .HasForeignKey("GrupoFamiliarId");

                    b.HasOne("projeto_financeiro_mvc.Models.UsuarioModel", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");

                    b.Navigation("GrupoFamiliar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.UsuarioModel", b =>
                {
                    b.HasOne("projeto_financeiro_mvc.Models.GrupoFamiliarModel", "GrupoFamiliar")
                        .WithMany("Usuarios")
                        .HasForeignKey("GrupoFamiliarId");

                    b.Navigation("GrupoFamiliar");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.ContaModel", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.GrupoFamiliarModel", b =>
                {
                    b.Navigation("Lancamentos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("projeto_financeiro_mvc.Models.UsuarioModel", b =>
                {
                    b.Navigation("Contas");

                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
